name: Video Downloader and Uploader

on:
  workflow_dispatch:
    inputs:
      m3u8_url:
        description: 'm3u8 URL'
        required: true
        type: string
      output_name:
        description: 'Output filename (without extension)'
        required: true
        type: string
      serial_mode:
        description: 'Serial Mode (429 Avoidance)'
        required: false
        type: boolean
        default: false

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        # 1. apt-get updateを省略し、必要なものだけを即座にインストール
        sudo apt-get install -y aria2 parallel age ffmpeg
        
        # 2. Pythonパッケージもキャッシュなしで高速インストール
        pip install --no-cache-dir huggingface_hub

    - name: Setup Secrets
      run: |
        # GitHubのSecretsからageの受信者鍵とHFのトークンを設定
        echo "${{ secrets.AGE_RECIPIENT }}" > recipient.txt
        echo "HF_TOKEN=${{ secrets.HF_TOKEN }}" >> $GITHUB_ENV

    - name: Run script
      run: |
        # 実行権限を与えてスクリプトを実行
        chmod +x ./download.sh
        
        # シリアルモードの判定
        OPTIONS=""
        if [ "${{ inputs.serial_mode }}" = "true" ]; then
          OPTIONS="-s"
        fi
        
        ./download.sh $OPTIONS "${{ inputs.m3u8_url }}" "${{ inputs.output_name }}"
